name: Check & Fix Styling

on:
  pull_request:
    branches:
      - master
    paths:
      - '**.php'

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO }}

      - name: Laravel Pint
        uses: aglipanci/laravel-pint-action@1.0.0
        with:
          preset: laravel

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: PHP Linting (Pint)
